[buildPlans.lim]
family = "lim"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.lim.variants.design]
i = "serifed-diagonal-tailed"
l = "serifed-diagonal-tailed"

[buildPlans.lim.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.lim.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.lim.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"