[buildPlans.basic-latin-aw500]
family = "Basic Latin AW500"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.basic-latin-aw500.variants.design]
capital-a = "curly-tri-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-serifless-capped"
capital-h = "serifed"
capital-i = "short-serifed"
capital-j = "serifed-symmetric"
capital-k = "straight-serifed"
capital-l = "serifed"
capital-m = "slanted-sides-flat-bottom-serifed"
capital-n = "standard-serifed"
capital-p = "open-serifed"
capital-q = "crossing-baseline"
capital-r = "curly-serifed"
capital-s = "bilateral-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded-bilateral-motion-serifed"
capital-v = "straight-serifed"
capital-w = "straight-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "straight-serifed"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "serifless"
d = "toothed-serifed"
e = "rounded"
f = "flat-hook-serifless"
g = "single-storey-serifless"
h = "straight-serifed"
i = "tailed-serifed"
j = "serifed"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "serifed"
n = "straight-motion-serifed"
p = "eared-serifed"
q = "straight-serifed"
r = "serifed"
s = "serifless"
t = "flat-hook"
u = "toothed-motion-serifed"
v = "straight-serifless"
w = "straight-flat-top-serifed"
x = "straight-serifless"
y = "straight-serifed"
z = "straight-serifless-with-crossbar"
long-s = "bent-hook-tailed"
eszet = "longs-s-lig-descending-serifless"
lower-eth = "curly-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "flat-top"
lower-iota = "diagonal-tailed"
capital-lambda = "straight-top-serifed"
zero = "slashed"
one = "no-base-long-top-serif"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "oblique-upper-left-bar"
six = "straight-bar"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "through-cap"
percent = "rings-continuous-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner-flat-hooked"

[buildPlans.basic-latin-aw500.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.basic-latin-aw500.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.basic-latin-aw500.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"